# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iO9zEYwl56D-jTS_YNSrnHfudLq8amjO
"""



import streamlit as st
import preprocessor , helper

st.sidebar.title('whatsapp chat analyser')
uploaded_file = st.sidebar.file_uploader('choose a file')
if uploaded_file is not None:
    bytes_data = uploaded_file.getvalue()
    data = bytes_data.decode('utf-8')
    df = preprocessor.preprocessor(data)
    st.dataframe(df)
    
    #fetch unique user
    user_list = df['user'].unique().tolist()
    user_list.sort()
    user_list.insert(0,'Overall')
    selected_user = st.sidebar.selectbox('show analysis wrt',user_list)

    if st.sidebar.button('show analysis'):
      num_messages, words = helper.fetch_stats(selected_user,df)

      col1, col2, col3, col4 = st.columns(4)

      with col1:
        st.header('total messages')
        st.title(num_messages)
      with col1:
        st.header('total words')
        st.title(words)