# -*- coding: utf-8 -*-
"""helper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m7p1lyxd7geZEKiyumTINPmBgjHqycM6
"""

def fetch_stats(selected_user,df):
  if selected_user =='Overall':
    return df.shape[0]
  else:
      return df[df['user']==selected_user].shape[0]